import { mkdir, writeFile, readdir } from "fs/promises";
import { join, basename } from "path";
import type { TemplateMetadata, TemplateSection, TemplateComponent } from "./types";

// Maps each component type to its Typst function call shape.
const COMPONENT_TYPST: Record<TemplateComponent["type"], (props: Record<string, unknown>) => string> = {
  "stat-cell": (p) =>
    `#stat-cell(label: "${p.label ?? ""}", value: "${p.value ?? ""}", trend: "${p.trend ?? ""}")`,
  "section-header": (p) =>
    `#section-header("${p.title ?? ""}")`,
  "metric-strip": (p) =>
    `#metric-strip(metrics: (${serializeArray(p.metrics)}))`,
  "callout-box": (p) =>
    `#callout-box(icon: "${p.icon ?? "!"}", body: [${p.body ?? ""}])`,
  "page-footer": (p) =>
    `#page-footer(left: "${p.left ?? ""}", right: "${p.right ?? ""}")`,
  "text-block": (p) =>
    `#text-block[${p.content ?? ""}]`,
  "table": (p) =>
    `#data-table(columns: (${serializeArray(p.columns)}), rows: data.${String(p.dataKey ?? "rows")})`,
};

function serializeArray(val: unknown): string {
  if (!Array.isArray(val)) return "";
  return val.map((v) => (typeof v === "string" ? `"${v}"` : String(v))).join(", ");
}

function renderComponent(component: TemplateComponent): string {
  const renderer = COMPONENT_TYPST[component.type];
  if (!renderer) return `// unknown component: ${component.type}`;
  return renderer(component.props);
}

function renderSection(section: TemplateSection): string {
  const componentLines = section.components.map((c) => `  ${renderComponent(c)}`).join("\n");
  return `// ── ${section.title} (${section.type}) ──\n${componentLines}`;
}

export class TemplateSaver {
  /**
   * Generate Typst source from the template metadata.
   *
   * The output always:
   *  - imports the spell-brand library
   *  - imports data.yaml for variable substitution
   *  - renders each section in declaration order
   */
  generateTypst(metadata: TemplateMetadata): string {
    const sectionBodies = metadata.sections.map(renderSection).join("\n\n");

    // Build a Typst comment listing declared variables so template consumers
    // know what data keys to populate in data.yaml.
    const varDocs = Object.entries(metadata.variables)
      .map(([k, v]) => `//   ${k}: ${v.type}${v.required ? " (required)" : ""} — ${v.description}`)
      .join("\n");

    return [
      `// Generated by Spell template-builder — do not edit manually`,
      `// Template: ${metadata.name}`,
      `// ${metadata.description}`,
      `//`,
      `// Variables (populate in data.yaml):`,
      varDocs || "//   (none)",
      ``,
      `#import "spell-brand.typ": *`,
      `#let data = yaml("data.yaml")`,
      ``,
      sectionBodies,
    ].join("\n");
  }

  /**
   * Persist metadata + generated Typst source to `outputDir`.
   *
   * File names are derived from `metadata.name` (lowercased, spaces→hyphens).
   * When a name collision is detected the numeric suffix strategy is used:
   *   my-template.typ, my-template-2.typ, my-template-3.typ, …
   */
  async save(
    metadata: TemplateMetadata,
    outputDir: string
  ): Promise<{ metadataPath: string; typstPath: string }> {
    await mkdir(outputDir, { recursive: true });

    const slug = metadata.name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
    const baseName = slug || "template";

    const uniqueName = await this.#resolveUniqueName(outputDir, baseName);

    const metadataPath = join(outputDir, `${uniqueName}.json`);
    const typstPath = join(outputDir, `${uniqueName}.typ`);

    await writeFile(metadataPath, JSON.stringify(metadata, null, 2), "utf-8");
    await writeFile(typstPath, this.generateTypst(metadata), "utf-8");

    return { metadataPath, typstPath };
  }

  /**
   * Return a base name that does not collide with existing files in `dir`.
   * Checks for both .json and .typ — both must be free before the name is accepted.
   */
  async #resolveUniqueName(dir: string, baseName: string): Promise<string> {
    let entries: string[];
    try {
      const dirents = await readdir(dir);
      entries = dirents.map((d) => (typeof d === "string" ? d : (d as { name: string }).name));
    } catch {
      // Directory doesn't exist yet or is unreadable — no collision possible.
      return baseName;
    }

    const taken = new Set(entries.map((e) => basename(e, e.includes(".") ? `.${e.split(".").pop()}` : "")));

    if (!taken.has(baseName)) return baseName;

    let suffix = 2;
    while (taken.has(`${baseName}-${suffix}`)) {
      suffix++;
    }
    return `${baseName}-${suffix}`;
  }
}
