//! Build script for pi-natives.
//!
//! Two responsibilities:
//! 1. `napi_build::setup()` for the NAPI cdylib.
//! 2. Auto-generate the SchemeProfile registry table by scanning
//!    `src/code_path/uri/` for `*.rs` files (excluding `mod.rs`). Each
//!    profile module must expose `pub fn build(ctx: Option<&SessionContext>)
//!    -> SchemeProfile`.
//!
//! Adding a scheme = one new `.rs` file in `src/code_path/uri/`. The build
//! script picks it up automatically and includes it in the registry.
//!
//! See PLAN-310 for the design.

use std::{env, fs, path::PathBuf};

fn main() {
	napi_build::setup();
	generate_scheme_registry();
}

fn generate_scheme_registry() {
	let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
	let uri_dir = PathBuf::from(&manifest_dir).join("src/code_path/uri");
	let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
	let out_file = out_dir.join("scheme_factories.rs");

	println!("cargo:rerun-if-changed={}", uri_dir.display());

	let mut names: Vec<String> = Vec::new();
	if uri_dir.exists() {
		for entry in fs::read_dir(&uri_dir).expect("read uri/ dir") {
			let entry = entry.expect("dir entry");
			let path = entry.path();
			if path.extension().and_then(|s| s.to_str()) != Some("rs") {
				continue;
			}
			let stem = match path.file_stem().and_then(|s| s.to_str()) {
				Some(s) => s.to_string(),
				None => continue,
			};
			if stem == "mod" || stem.starts_with("_") {
				continue;
			}
			println!("cargo:rerun-if-changed={}", path.display());
			names.push(stem);
		}
	}
	names.sort();

	let mut out = String::new();
	out.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n");
	out.push_str("// Source: scan of crates/pi-natives/src/code_path/uri/*.rs\n\n");
	// Use absolute #[path] so the include! site doesn't need to live next to the source.
	for n in &names {
		let abs = uri_dir.join(format!("{n}.rs"));
		out.push_str(&format!(
			"#[path = {:?}]\npub mod {n};\n",
			abs.display().to_string()
		));
	}
	out.push_str("\nuse pi_code_path::{SchemeProfile, SessionContext};\n\n");
	out.push_str(
		"/// Auto-registry of static SchemeProfile factories. Populated by build.rs from\n\
		 /// the contents of crates/pi-natives/src/code_path/uri/.\n\
		 pub static SCHEME_FACTORIES: &[fn(Option<&SessionContext>) -> SchemeProfile] = &[\n",
	);
	for n in &names {
		out.push_str(&format!("\t{n}::build,\n"));
	}
	out.push_str("];\n");

	fs::write(&out_file, out).expect("write scheme_factories.rs");
}
