//! Build script for pi-natives.
//!
//! Two responsibilities:
//! 1. `napi_build::setup()` for the NAPI cdylib.
//! 2. Auto-generate the SchemeProfile registry table by scanning
//!    `src/code_path/uri/` for `*.rs` files (excluding `mod.rs`). Each
//!    profile module must expose `pub fn build(ctx: Option<&SessionContext>)
//!    -> SchemeProfile`.
//!
//! Adding a scheme = one new `.rs` file in `src/code_path/uri/`. The build
//! script picks it up automatically and includes it in the registry.
//!
//! See PLAN-310 for the design.

use std::{env, fs, path::PathBuf};

fn main() {
	napi_build::setup();
	generate_scheme_registry();
	generate_pi_docs_index();
}

/// Walks `<workspace>/docs/**/*.md` and emits a `phf::Map` literal of
/// (filename → file content) suitable for `ContentLoader::Static`.
///
/// Output: `$OUT_DIR/pi_docs_index.rs`, included by `uri/pi.rs`.
fn generate_pi_docs_index() {
	let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
	let workspace = PathBuf::from(&manifest_dir).join("../..");
	let docs_dir = workspace.join("docs");
	let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
	let out_file = out_dir.join("pi_docs_index.rs");

	println!("cargo:rerun-if-changed={}", docs_dir.display());

	let mut entries: Vec<(String, String)> = Vec::new();
	if docs_dir.exists() {
		walk_md(&docs_dir, &docs_dir, &mut entries);
	}
	entries.sort_by(|a, b| a.0.cmp(&b.0));

	let mut out = String::new();
	out.push_str("// AUTO-GENERATED by build.rs. Source: <workspace>/docs/**/*.md\n\n");
	out.push_str("pub static EMBEDDED_DOCS: phf::Map<&'static str, &'static str> = phf::phf_map! {\n");
	for (rel, contents) in &entries {
		out.push_str(&format!(
			"\t{:?} => {:?},\n",
			rel,
			contents
		));
	}
	out.push_str("};\n\n");
	out.push_str("pub static EMBEDDED_DOC_FILENAMES: &[&str] = &[\n");
	for (rel, _) in &entries {
		out.push_str(&format!("\t{:?},\n", rel));
	}
	out.push_str("];\n");

	fs::write(&out_file, out).expect("write pi_docs_index.rs");
}

fn walk_md(root: &std::path::Path, dir: &std::path::Path, out: &mut Vec<(String, String)>) {
	let Ok(rd) = fs::read_dir(dir) else { return };
	for entry in rd.flatten() {
		let path = entry.path();
		if path.is_dir() {
			println!("cargo:rerun-if-changed={}", path.display());
			walk_md(root, &path, out);
			continue;
		}
		if path.extension().and_then(|s| s.to_str()) != Some("md") {
			continue;
		}
		let rel = path.strip_prefix(root).unwrap_or(&path);
		let rel_str = rel.to_string_lossy().replace('\\', "/");
		let content = fs::read_to_string(&path).unwrap_or_default();
		out.push((rel_str, content));
	}
}

fn generate_scheme_registry() {
	let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
	let uri_dir = PathBuf::from(&manifest_dir).join("src/code_path/uri");
	let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
	let out_file = out_dir.join("scheme_factories.rs");

	println!("cargo:rerun-if-changed={}", uri_dir.display());

	let mut names: Vec<String> = Vec::new();
	if uri_dir.exists() {
		for entry in fs::read_dir(&uri_dir).expect("read uri/ dir") {
			let entry = entry.expect("dir entry");
			let path = entry.path();
			if path.extension().and_then(|s| s.to_str()) != Some("rs") {
				continue;
			}
			let stem = match path.file_stem().and_then(|s| s.to_str()) {
				Some(s) => s.to_string(),
				None => continue,
			};
			if stem == "mod" || stem.starts_with("_") {
				continue;
			}
			println!("cargo:rerun-if-changed={}", path.display());
			names.push(stem);
		}
	}
	names.sort();

	let mut out = String::new();
	out.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n");
	out.push_str("// Source: scan of crates/pi-natives/src/code_path/uri/*.rs\n\n");
	// Use absolute #[path] so the include! site doesn't need to live next to the source.
	for n in &names {
		let abs = uri_dir.join(format!("{n}.rs"));
		out.push_str(&format!(
			"#[path = {:?}]\npub mod {n};\n",
			abs.display().to_string()
		));
	}
	out.push_str("\nuse pi_code_path::{SchemeProfile, SessionContext};\n\n");
	out.push_str(
		"/// Auto-registry of static SchemeProfile factories. Populated by build.rs from\n\
		 /// the contents of crates/pi-natives/src/code_path/uri/.\n\
		 pub static SCHEME_FACTORIES: &[fn(Option<&SessionContext>) -> SchemeProfile] = &[\n",
	);
	for n in &names {
		out.push_str(&format!("\t{n}::build,\n"));
	}
	out.push_str("];\n");

	fs::write(&out_file, out).expect("write scheme_factories.rs");
}
