//! Native utilities exported via N-API for the Oh My Pi toolchain.
//!
//! # Overview
//! High-performance primitives for clipboard access, grep, file discovery,
//! ANSI-aware text measurement, syntax highlighting, HTML-to-Markdown
//! conversion, and image processing.
//!
//! # Example
//! ```ignore
//! use pi_natives::text::visible_width;
//!
//! let width = visible_width("hello");
//! assert_eq!(width, 5);
//! ```
//!
//! # Architecture
//! ```text
//! JS (packages/natives) -> N-API -> Rust modules (clipboard/fd/find/grep/html/highlight/image/text)
//! ```

#![allow(clippy::trailing_empty_array, reason = "generated by napi macro")]
#![allow(clippy::trivially_copy_pass_by_ref, reason = "napi env idiom")]
use std::{
	sync::{Arc, OnceLock},
	time::SystemTime,
};

use pi_code_engine::{
	BrokerEndpoint, SocketCoordClient, buffer::BufferRegistry, language::LanguageRegistry,
	watcher::FileWatcher,
};

use crate::code_path::edit_history::EditHistory;

pub(crate) fn language_registry() -> Arc<LanguageRegistry> {
	static LANGUAGE_REGISTRY: OnceLock<Arc<LanguageRegistry>> = OnceLock::new();
	LANGUAGE_REGISTRY
		.get_or_init(|| {
			Arc::new(LanguageRegistry::with_builtins().expect("failed to load language profiles"))
		})
		.clone()
}

pub(crate) fn buffer_registry() -> &'static BufferRegistry {
	static BUFFER_REGISTRY: OnceLock<BufferRegistry> = OnceLock::new();
	BUFFER_REGISTRY.get_or_init(|| {
		let endpoint = BrokerEndpoint::default_for("napi".into());
		let watcher = FileWatcher::new().ok();
		// BUG-414: subscribe code_graph_cache invalidation to filesystem
		// changes so edge queries reflect the current state of the repo.
		// FUP-100: also invalidate the semantic cache — external file
		// changes (build scripts, branch switches, etc.) need to tear down
		// the per-workspace LSP so the next semantic query respawns with
		// fresh state. This is heavy but correct; the lighter-weight
		// EditRecorder path below fires didChange without tearing down.
		if let Some(ref w) = watcher {
			w.on_change(Box::new(|path| {
				crate::code_graph_cache::invalidate_for_file(path);
				crate::semantic_cache::invalidate_for_file(path);
			}));
		}
		let registry = BufferRegistry::new_with_coord(
			language_registry(),
			watcher,
			Arc::new(SocketCoordClient::new(endpoint)),
		);
		let recorder = Arc::new(|record: pi_code_engine::buffer::EditRecord| {
			// FUP-100: agent-driven edit → didChange to every warm LSP that
			// has this file open. Light-weight: no respawn, just a version
			// bump + content delta on the existing client. The next
			// `#hover` / `#signature` query against the file sees the new
			// text without re-reading disk.
			crate::semantic_cache::notify_buffer_change(&record.file, &record.after);

			let workspace = pi_code_engine::workspace_root_for(&record.file);
			// PLAN-338 B: prefer the session-unified log
			// (`<session_dir>/edit-history.jsonl`) when a session dir is active on
			// this thread, so ONE log spans every workspace the session touches.
			// Fall back to the legacy per-workspace shard otherwise (headless/test;
			// also the natural fresh-start for pre-unification sessions).
			let path = match crate::code_path::edit_history::current_session_dir() {
				Some(dir) => crate::code_path::edit_history::session_log_path(&dir),
				None => workspace.join(".spell").join("edit-history.jsonl"),
			};
			let history = crate::code_path::edit_history::JsonlHistory::new(path);
			// PLAN-338 C: capture HEAD at record time (before `record.file` moves).
			// This is the commit the edit was made AGAINST (provenance), NOT proof the
			// edit is committed — the undo guard re-checks live git state
			// (commit_guard::is_committed). Fail-open None when not a repo.
			let commit_at_record = crate::code_path::commit_guard::head_sha(&record.file);
			history.record(crate::code_path::edit_history::EditEntry {
				id:          crate::code_path::edit_history::next_entry_id(),
				session_id:  record.session_id,
				agent_label: String::new(),
				file:        record.file,
				before:      record.before,
				after:       record.after,
				diff:        record.diff,
				timestamp:   SystemTime::now(),
				commit:      commit_at_record,
				reverted:    false,
				// Stamp the group active on this thread (set by the edit command
				// handler for one logical `edit` invocation) so a multi-file
				// operation's entries undo/redo atomically.
				group_id:    crate::code_path::edit_history::current_edit_group(),
				workspace:   workspace.to_string_lossy().into_owned(),
			});
		});
		registry.with_edit_recorder(recorder)
	})
}

pub mod appearance;
pub mod ast;
pub mod clipboard;
pub mod code_buffer;
pub mod code_graph;
// P5.A (PLAN-336): the workspace graph cache moved to pi-kernel (host-agnostic,
// shared with the BEAM NIF). Re-exported here so existing
// `crate::code_graph_cache::*` call sites keep resolving unchanged.
pub use pi_kernel::graph_cache as code_graph_cache;
pub mod code_path;
pub mod semantic_cache;
// PLAN-315 W2: client-side transport to pi-knowledge-worker.
// Promoted to `pub` so integration tests + future crates can reach
// `capabilities()`, `knowledge_request()`, and the Capabilities type
// without going through NAPI.
pub mod embedding_worker;

// PLAN-315 W4: client-side push-subscribe handle.
#[cfg(unix)]
pub mod knowledge_client;

// FEAT-784: NAPI wrapper around KnowledgeSubscription for the
// MemoryStatusController push-update path.
#[cfg(unix)]
pub mod knowledge_napi;

// PLAN-310: kernel-side scheme exec — bash URI pre-processing
// and CodePath execution for kernel-owned schemes.
pub mod exec;
pub mod fd;
pub mod fs_cache;
pub mod glob;
pub mod glob_util;
pub mod grep;
pub mod highlight;
pub mod html;
pub mod image;
pub mod keys;
pub mod language;
pub mod org_buffer;
pub mod org_index;
pub mod prof;
pub mod projfs_overlay;
pub mod ps;
pub mod pty;
pub mod recall_engine;
pub mod shell;
pub mod task;
pub mod text;
pub mod typst_surface;
pub(crate) mod utils;
