//! Native utilities exported via N-API for the Oh My Pi toolchain.
//!
//! # Overview
//! High-performance primitives for clipboard access, grep, file discovery,
//! ANSI-aware text measurement, syntax highlighting, HTML-to-Markdown
//! conversion, and image processing.
//!
//! # Example
//! ```ignore
//! use pi_natives::text::visible_width;
//!
//! let width = visible_width("hello");
//! assert_eq!(width, 5);
//! ```
//!
//! # Architecture
//! ```text
//! JS (packages/natives) -> N-API -> Rust modules (clipboard/fd/find/grep/html/highlight/image/text)
//! ```

#![allow(clippy::trailing_empty_array, reason = "generated by napi macro")]
#![allow(clippy::trivially_copy_pass_by_ref, reason = "napi env idiom")]
use std::sync::{Arc, OnceLock};

use pi_code_engine::{
	BrokerEndpoint, SocketCoordClient, buffer::BufferRegistry, language::LanguageRegistry,
	watcher::FileWatcher,
};

pub(crate) fn language_registry() -> Arc<LanguageRegistry> {
	static LANGUAGE_REGISTRY: OnceLock<Arc<LanguageRegistry>> = OnceLock::new();
	LANGUAGE_REGISTRY
		.get_or_init(|| {
			Arc::new(LanguageRegistry::with_builtins().expect("failed to load language profiles"))
		})
		.clone()
}

pub(crate) fn buffer_registry() -> &'static BufferRegistry {
	static BUFFER_REGISTRY: OnceLock<BufferRegistry> = OnceLock::new();
	BUFFER_REGISTRY.get_or_init(|| {
		let endpoint = BrokerEndpoint::default_for("napi".into());
		BufferRegistry::new_with_coord(
			language_registry(),
			FileWatcher::new().ok(),
			Arc::new(SocketCoordClient::new(endpoint)),
		)
	})
}

pub mod appearance;
pub mod ast;
pub mod clipboard;
pub mod code_buffer;
pub mod code_graph;
pub(crate) mod embedding_worker;
pub mod fd;
pub mod fs_cache;
pub mod glob;
pub mod glob_util;
pub mod grep;
pub mod highlight;
pub mod html;
pub mod image;
pub mod keys;
pub mod language;
pub mod org_buffer;
pub mod org_index;
pub mod prof;
pub mod projfs_overlay;
pub mod ps;
pub mod pty;
pub mod shell;
pub mod task;
pub mod text;
pub mod typst_surface;
pub(crate) mod utils;
