[package]
name = "pi-text-search"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
grep-regex = "0.1"
grep-searcher = "0.1"
grep-matcher = "0.1"
globset = "0.4"
ignore = "0.4"
rayon = "1.10"
smallvec = { version = "1.15.1", features = ["union", "const_new"] }
thiserror = "2"

[dev-dependencies]
tempfile = "3"
