use std::{collections::HashMap, env, fmt::Write as _, fs, path::Path};

use serde::Deserialize;

#[derive(Deserialize)]
struct NodeType {
	r#type:   String,
	named:    bool,
	#[serde(default)]
	fields:   HashMap<String, FieldInfo>,
	#[serde(default)]
	children: Option<ChildrenInfo>,
	#[serde(default)]
	subtypes: Option<Vec<SubType>>,
}

#[derive(Deserialize)]
struct FieldInfo {
	#[allow(dead_code, reason = "required for deserialization")]
	multiple: bool,
	#[allow(dead_code, reason = "required for deserialization")]
	required: bool,
	types:    Vec<SubType>,
}

#[derive(Deserialize)]
struct ChildrenInfo {
	#[allow(dead_code, reason = "required for deserialization")]
	multiple: bool,
	#[allow(dead_code, reason = "required for deserialization")]
	required: bool,
	types:    Vec<SubType>,
}

#[derive(Deserialize)]
struct SubType {
	r#type: String,
	named:  bool,
}

struct GrammarSource {
	/// Name used for the output file: grammar_{name}.rs
	name:           &'static str,
	/// Path to node-types.json relative to crate source in the cargo registry.
	/// We search for the crate directory by matching the package prefix.
	package_prefix: &'static str,
	/// Sub-path within the crate directory to find node-types.json.
	json_subpath:   &'static str,
}

const GRAMMARS: &[GrammarSource] = &[
	GrammarSource {
		name:           "typescript",
		package_prefix: "tree-sitter-typescript-",
		json_subpath:   "typescript/src/node-types.json",
	},
	GrammarSource {
		name:           "rust",
		package_prefix: "tree-sitter-rust-",
		json_subpath:   "src/node-types.json",
	},
	GrammarSource {
		name:           "python",
		package_prefix: "tree-sitter-python-",
		json_subpath:   "src/node-types.json",
	},
	GrammarSource {
		name:           "elixir",
		package_prefix: "tree-sitter-elixir-",
		json_subpath:   "src/node-types.json",
	},
];

fn main() {
	let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");

	for grammar in GRAMMARS {
		match find_and_generate(grammar, &out_dir) {
			Ok(()) => {},
			Err(e) => {
				println!("cargo:warning=Failed to generate rules for {}: {e}", grammar.name);
				generate_empty(&out_dir, grammar.name);
			},
		}
	}
}

fn find_and_generate(grammar: &GrammarSource, out_dir: &str) -> Result<(), String> {
	let json_path = find_node_types_json(grammar)?;
	let content = fs::read_to_string(&json_path)
		.map_err(|e| format!("failed to read {}: {e}", json_path.display()))?;
	let node_types: Vec<NodeType> =
		serde_json::from_str(&content).map_err(|e| format!("failed to parse JSON: {e}"))?;

	let code = generate_grammar_module(&node_types);
	let out_path = Path::new(out_dir).join(format!("grammar_{}.rs", grammar.name));
	fs::write(&out_path, code)
		.map_err(|e| format!("failed to write {}: {e}", out_path.display()))?;

	// Tell cargo to rebuild if the source JSON changes.
	println!("cargo:rerun-if-changed={}", json_path.display());

	Ok(())
}

fn find_node_types_json(grammar: &GrammarSource) -> Result<std::path::PathBuf, String> {
	// Strategy: scan cargo registry src directories for the matching crate prefix.
	let home = env::var("CARGO_HOME")
		.or_else(|_| env::var("HOME").map(|h| format!("{h}/.cargo")))
		.map_err(|_| "cannot determine CARGO_HOME".to_string())?;

	let registry_src = Path::new(&home).join("registry/src");
	if !registry_src.exists() {
		return Err(format!("cargo registry not found at {}", registry_src.display()));
	}

	// Iterate registry index directories (e.g., index.crates.io-HASH/)
	let entries = fs::read_dir(&registry_src).map_err(|e| format!("cannot read registry: {e}"))?;

	for entry in entries.flatten() {
		let index_dir = entry.path();
		if !index_dir.is_dir() {
			continue;
		}
		// Look for crate directories matching our prefix
		let crate_entries =
			fs::read_dir(&index_dir).map_err(|e| format!("cannot read index dir: {e}"))?;

		for crate_entry in crate_entries.flatten() {
			let name = crate_entry.file_name();
			let name_str = name.to_string_lossy();
			if name_str.starts_with(grammar.package_prefix) {
				let candidate = crate_entry.path().join(grammar.json_subpath);
				if candidate.exists() {
					return Ok(candidate);
				}
			}
		}
	}

	Err(format!(
		"node-types.json not found for {} (searched {})",
		grammar.name,
		registry_src.display()
	))
}

fn generate_grammar_module(node_types: &[NodeType]) -> String {
	let mut code = String::with_capacity(64 * 1024);

	writeln!(code, "// Generated by build.rs from tree-sitter node-types.json").unwrap();
	writeln!(code, "// DO NOT EDIT").unwrap();
	writeln!(code).unwrap();

	// Generate the grammar() function
	writeln!(
		code,
		"#[allow(unused_mut, clippy::field_reassign_with_default, clippy::vec_init_then_push, \
		 clippy::too_many_lines, reason = \"generated code\")]"
	)
	.unwrap();
	writeln!(code, "pub fn grammar() -> GeneratedGrammar {{").unwrap();
	writeln!(code, "\tlet mut production_rules = HashMap::new();").unwrap();
	writeln!(code, "\tlet mut inverse_rules: HashMap<String, Vec<String>> = HashMap::new();")
		.unwrap();
	writeln!(code, "\tlet mut all_types = Vec::new();").unwrap();
	writeln!(code, "\tlet mut supertypes = Vec::new();").unwrap();
	writeln!(code).unwrap();

	for nt in node_types {
		if !nt.named {
			continue;
		}

		// Collect all types
		writeln!(code, "\tall_types.push({:?}.to_string());", nt.r#type).unwrap();

		// Supertypes: nodes with subtypes array
		if let Some(subtypes) = &nt.subtypes {
			writeln!(code, "\tsupertypes.push({:?}.to_string());", nt.r#type).unwrap();

			// Add inverse rules: each subtype -> this supertype
			for st in subtypes {
				if st.named {
					writeln!(
						code,
						"\tinverse_rules.entry({:?}.to_string()).or_default().push({:?}.to_string());",
						st.r#type, nt.r#type
					)
					.unwrap();
				}
			}
			// Supertypes don't have production rules themselves
			continue;
		}

		// Production rules for nodes with fields or children
		if nt.fields.is_empty() && nt.children.is_none() {
			continue;
		}

		writeln!(code, "\t{{").unwrap();
		writeln!(code, "\t\tlet mut rule = ProductionRule::default();").unwrap();

		// Fields
		for (field_name, field_info) in &nt.fields {
			let child_types: Vec<&str> = field_info
				.types
				.iter()
				.filter(|t| t.named)
				.map(|t| t.r#type.as_str())
				.collect();
			if !child_types.is_empty() {
				writeln!(
					code,
					"\t\trule.fields.insert({field_name:?}.to_string(), vec![{}]);",
					child_types
						.iter()
						.map(|t| format!("{t:?}.to_string()"))
						.collect::<Vec<_>>()
						.join(", ")
				)
				.unwrap();

				// Add inverse rules: each child type -> this parent
				for ct in &child_types {
					writeln!(
						code,
						"\t\tinverse_rules.entry({ct:?}.to_string()).or_default().push({:?}.\
						 to_string());",
						nt.r#type
					)
					.unwrap();
				}
			}
		}

		// Unnamed children
		if let Some(children) = &nt.children {
			let child_types: Vec<&str> = children
				.types
				.iter()
				.filter(|t| t.named)
				.map(|t| t.r#type.as_str())
				.collect();
			if !child_types.is_empty() {
				writeln!(
					code,
					"\t\trule.unnamed_children = vec![{}];",
					child_types
						.iter()
						.map(|t| format!("{t:?}.to_string()"))
						.collect::<Vec<_>>()
						.join(", ")
				)
				.unwrap();
			}
		}

		writeln!(code, "\t\tproduction_rules.insert({:?}.to_string(), rule);", nt.r#type).unwrap();
		writeln!(code, "\t}}").unwrap();
	}

	writeln!(code).unwrap();
	writeln!(code, "\t// Deduplicate inverse rules").unwrap();
	writeln!(code, "\tfor parents in inverse_rules.values_mut() {{").unwrap();
	writeln!(code, "\t\tparents.sort();").unwrap();
	writeln!(code, "\t\tparents.dedup();").unwrap();
	writeln!(code, "\t}}").unwrap();
	writeln!(code).unwrap();
	writeln!(
		code,
		"\tGeneratedGrammar {{ production_rules, inverse_rules, all_types, supertypes }}"
	)
	.unwrap();
	writeln!(code, "}}").unwrap();

	code
}

fn generate_empty(out_dir: &str, name: &str) {
	let code = r"// Generated by build.rs — grammar not found, empty fallback
// DO NOT EDIT

pub fn grammar() -> GeneratedGrammar {
	GeneratedGrammar {
		production_rules: HashMap::new(),
		inverse_rules: HashMap::new(),
		all_types: Vec::new(),
		supertypes: Vec::new(),
	}
}
";
	let out_path = Path::new(out_dir).join(format!("grammar_{name}.rs"));
	fs::write(out_path, code).ok();
}
